[mypy]
python_version = 3.10
ignore_missing_imports = true
warn_return_any = true
warn_unused_configs = true
no_strict_optional = false

[mypy-chess_coach.chess_board.*]
ignore_errors = true

[mypy-chess_coach.main_window.*]
ignore_errors = true

[mypy-chess_coach.coach_dashboard.*]
ignore_errors = true
