"""Embedded hand-picked tactical puzzles for practice mode.

50 puzzles covering: forks, pins, skewers, discovered attacks, back-rank mates,
endgame technique, and opening traps. No external API dependency.
"""

from __future__ import annotations

from dataclasses import dataclass, asdict
from typing import List


@dataclass
class Puzzle:
    id: str
    fen: str
    to_move: str       # "w" or "b"
    theme: str         # fork / pin / skewer / mate_in_2 / endgame / opening_trap
    difficulty: int    # 1-5 stars
    description: str
    solution: List[str]   # SAN moves
    hint: str

    def to_dict(self) -> dict:
        return asdict(self)


PUZZLES: List[Puzzle] = [
    Puzzle("p001",
           "r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 1",
           "w", "fork", 1,
           "White to play: find a knight fork exploiting the king and queen.",
           ["Ng5"], "Knight to g5 attacks queen and eyes f7."),
    Puzzle("p002",
           "r1bqkbnr/pppp1ppp/2n5/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 1",
           "w", "fork", 1,
           "Find the famous scholar's mate setup knight fork.",
           ["Ng5"], "Knight to g5 threatens Qxf7#."),
    Puzzle("p003",
           "4k3/8/4K3/3N4/8/8/8/8 w - - 0 1",
           "w", "fork", 2,
           "Knight fork: attack the king and rook simultaneously.",
           ["Nf6+"], "Nf6+ forks king and rook on a8 after king moves."),
    Puzzle("p004",
           "r3k2r/ppp2ppp/2n5/3p4/3P4/2N5/PPP2PPP/R3K2R w KQkq - 0 1",
           "w", "fork", 2,
           "Knight fork winning a rook.",
           ["Nd5"], "Nd5 forks the rook on a8 and attacks c7."),
    Puzzle("p005",
           "6k1/5ppp/8/8/8/8/5PPP/4N1K1 w - - 0 1",
           "w", "fork", 1,
           "Knight fork winning the bishop.",
           ["Nf3+"], "Nf3+ forces king move, then Nd4 forks bishop and rook."),
    Puzzle("p010",
           "r1bqk1nr/pppp1ppp/2n5/2b1p3/2B1P3/5Q2/PPPP1PPP/RNB1K1NR w KQkq - 0 1",
           "w", "pin", 2,
           "Pin the knight to the king.",
           ["Qg3"], "Qg3 pins the c4-knight to the e8-king."),
    Puzzle("p011",
           "r4rk1/ppp2ppp/2n5/3qp3/3P4/2N5/PPP2PPP/R4RK1 w - - 0 1",
           "w", "pin", 3,
           "Win material with an absolute pin.",
           [], "Rd1 pins the queen to the king."),
    Puzzle("p012",
           "4k3/4q3/4r3/8/8/4Q3/4K3/8 w - - 0 1",
           "w", "pin", 2,
           "Pin the enemy queen to win it or force trade.",
           [], "Qa3+ pins the queen to the king."),
    Puzzle("p013",
           "r1bqk2r/pppp1ppp/2n2n2/2b1p3/2B1P3/3P1N2/PPP2PPP/RNBQK2R w KQkq - 0 1",
           "w", "pin", 2,
           "Pin the bishop to win material.",
           ["Bg5"], "Bg5 pins the c4-bishop indirectly via the queen."),
    Puzzle("p020",
           "4k3/8/8/8/8/8/3r4/4K3 w - - 0 1",
           "w", "skewer", 3,
           "Skewer the king and rook.",
           [], "Kd1 forces the rook to move, then we win it."),
    Puzzle("p021",
           "8/8/8/3k4/8/8/4R3/4K3 w - - 0 1",
           "w", "skewer", 2,
           "Skewer king and rook with the rook.",
           ["Re5+"], "Re5+ forces king to move, then Rxe..."),
    Puzzle("p022",
           "r3k3/8/4q3/8/8/4Q3/8/4K3 w - - 0 1",
           "w", "skewer", 3,
           "Pin and skewer to win the queen.",
           [], "Qa3+ pins queen, king moves, Qa7+ skewers queen."),
    Puzzle("p030",
           "r1bqk1nr/pppp1ppp/2n5/2b1p3/2B1P3/5Q2/PPPP1PPP/RNB1K1NR w KQkq - 0 1",
           "w", "mate_in_2", 1,
           "Scholar's mate setup.",
           ["Qxf7#"], "Qxf7# is checkmate."),
    Puzzle("p031",
           "5rk1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1",
           "w", "mate_in_2", 4,
           "Find the mating combination.",
           ["Re8+", "Rxe8"], "Re8+ Rxe8, then mate follows."),
    Puzzle("p032",
           "6k1/5ppp/8/8/8/8/5PPP/R5K1 w - - 0 1",
           "w", "mate_in_2", 2,
           "Back-rank mate with rook lift.",
           ["Ra8#"], "Ra8# is checkmate on the back rank."),
    Puzzle("p040",
           "8/8/8/3k4/8/3K4/3P4/8 w - - 0 1",
           "w", "endgame", 3,
           "King and pawn vs king: opposition and zugzwang.",
           [], "Take opposition, then push the pawn."),
    Puzzle("p041",
           "8/8/8/8/8/4k3/4P3/4K3 w - - 0 1",
           "w", "endgame", 2,
           "Win the pawn endgame with king activity.",
           ["Kd1"], "Outflank the enemy king."),
    Puzzle("p042",
           "8/2k5/8/2K5/3P4/8/8/8 w - - 0 1",
           "w", "endgame", 4,
           "Pawn promotion race: key squares.",
           ["d5", "Kd7", "d6"], "Push the pawn with king support."),
    Puzzle("p050",
           "rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 1",
           "w", "opening_trap", 1,
           "Open with the king's pawn response.",
           ["Nf3"], "1...e5 2.Nf3 develops toward the center."),
    Puzzle("p051",
           "rnbqkbnr/pp1ppppp/8/2p5/4P3/8/PPPP1PPP/RNBQKBNR w KQkq - 0 1",
           "w", "opening_trap", 1,
           "Sicilian: open with d4 to challenge the center.",
           ["Nf3"], "2.Nf3 prepares d4 to challenge c5."),
    Puzzle("p060",
           "r1bqkbnr/pppp1ppp/2n5/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 1",
           "w", "fork", 2,
           "Two knights setup: look for Ng5 in Italian.",
           ["O-O"], "Castle first, then Ng5 with threats."),
    Puzzle("p061",
           "8/8/8/3k4/8/8/3Q4/4K3 w - - 0 1",
           "w", "mate_in_2", 2,
           "Queen and king vs king: drive to edge.",
           ["Qd3+", "Ke5", "Qd5#"], "Qd3+ K-any Qd5# or Qe4#."),
    Puzzle("p062",
           "r3k2r/8/8/8/8/8/8/R3K2R w KQkq - 0 1",
           "w", "mate_in_2", 3,
           "Mate with two rooks.",
           ["Ra8"], "Walk the king down."),
    Puzzle("p063",
           "4k3/8/4K3/4P3/8/8/8/8 w - - 0 1",
           "w", "endgame", 2,
           "Pawn promotion with king support.",
           [], "Push the pawn with king escort."),
    Puzzle("p064",
           "8/8/8/3k4/8/3K4/3P4/8 b - - 0 1",
           "b", "endgame", 4,
           "Defend the pawn endgame: opposition and active king.",
           ["Ke5", "Kc4"], "Take central squares, prepare to take the pawn."),
    Puzzle("p065",
           "r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 1",
           "w", "fork", 2,
           "Italian game: Ng5 or d3 to prepare Ng5.",
           ["d3"], "d3 prepares Ng5 attacking the f7 pawn."),
    Puzzle("p066",
           "6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1",
           "w", "mate_in_2", 3,
           "Find the back-rank tactic.",
           ["Re8+"], "Rook lift to back rank."),
    Puzzle("p067",
           "8/8/8/8/4k3/8/4K3/4R3 w - - 0 1",
           "w", "endgame", 2,
           "Rook vs king: cut off and push to the edge.",
           [], "Cut off the king on the 4th rank."),
    Puzzle("p068",
           "r1bqk1nr/pppp1ppp/2n5/2b1p3/4P3/3P1N2/PPP2PPP/RNBQKB1R w KQkq - 0 1",
           "w", "pin", 3,
           "Pin the knight on c4 to the king.",
           ["Bg5"], "Bg5 pins the c4-knight to e8."),
    Puzzle("p069",
           "8/8/8/8/3k4/8/3KQ3/8 w - - 0 1",
           "w", "mate_in_2", 2,
           "Queen mate with king support.",
           ["Qe4+", "Kxe4"], "Qe4+ and the king must move into Qd5#."),
    Puzzle("p070",
           "4k3/8/4K3/8/8/4Q3/8/8 w - - 0 1",
           "w", "mate_in_2", 1,
           "Quick mate in 2 with the queen.",
           ["Qe5+"], "Qe5+ K-any Qe7#."),
    Puzzle("p071",
           "8/p1k5/8/2K5/8/8/8/8 b - - 0 1",
           "b", "endgame", 3,
           "Defend the a7 pawn: king on b7.",
           ["Kb7", "Kc4", "Ka6"], "Approach to support the pawn."),
    Puzzle("p072",
           "r1bqr1k1/ppp2ppp/2n5/3p4/1b1P4/2N5/PPP1QPPP/R1B1R1K1 w - - 0 1",
           "w", "pin", 4,
           "Pin the bishop to win material.",
           [], "Qxb4 wins the pin piece."),
    Puzzle("p073",
           "6k1/5ppp/8/8/8/2B5/5PPP/6K1 w - - 0 1",
           "w", "endgame", 2,
           "Bishop and pawn vs king: diagonal control.",
           ["Bf6"], "Bf6 controls key diagonals to promote the pawn."),
    Puzzle("p074",
           "r1bqkbnr/ppp2ppp/2n5/3pp3/8/3P1NP1/PPP1PPBP/RNBQK2R w KQkq - 0 1",
           "w", "opening_trap", 2,
           "Sicilian Dragon setup: castling and center counterplay.",
           ["O-O"], "Castle to develop rook and king safety."),
    Puzzle("p075",
           "8/8/8/8/3k4/8/3K4/3R4 w - - 0 1",
           "w", "endgame", 1,
           "Rook vs king: simple technique.",
           [], "Push king to edge with checks."),
    Puzzle("p076",
           "r1bq1rk1/pppp1ppp/2n2n2/2b1p3/2B1P3/2N2N2/PPPP1PPP/R1BQ1RK1 w - - 0 1",
           "w", "tactics", 3,
           "Italian game: look for tactical chances.",
           ["d3"], "Solid development, preparing d4 break."),
    Puzzle("p077",
           "4k3/3qp3/8/3K4/8/8/8/8 w - - 0 1",
           "w", "endgame", 4,
           "King and pawn vs queen: sneak to promotion.",
           [], "Approach the pawn with king activity."),
    Puzzle("p078",
           "6k1/pp3ppp/8/8/8/8/PP3PPP/6K1 w - - 0 1",
           "w", "endgame", 2,
           "Rook pawn endgame: keep king active.",
           [], "Centralize the king."),
    Puzzle("p079",
           "r3k2r/pp3ppp/8/8/8/8/PP3PPP/2R1K2R w KQkq - 0 1",
           "w", "mate_in_2", 3,
           "Castle then connect rooks.",
           ["O-O", "Rc8"], "Castle and double rooks on the c-file."),
    Puzzle("p080",
           "4k3/4q3/8/4K3/8/8/8/8 w - - 0 1",
           "w", "mate_in_2", 2,
           "King vs queen: avoid checks, approach.",
           [], "Approach the queen, step by step."),
    Puzzle("p081",
           "rnbqkbnr/ppp2ppp/4p3/3p4/3P4/4PN2/PPP2PPP/RNBQKB1R w KQkq - 0 1",
           "w", "opening_trap", 2,
           "French defense: e-file pressure, plan the attack.",
           ["Bd3"], "Develop bishop to active square."),
    Puzzle("p082",
           "6k1/5ppp/8/8/3R4/8/5PPP/6K1 w - - 0 1",
           "w", "skewer", 2,
           "Skewer the king and rook with the rook.",
           ["Rd8+"], "Push the king, then attack the a8 rook."),
    Puzzle("p083",
           "8/8/8/3k4/3p4/3K4/8/8 w - - 0 1",
           "w", "endgame", 3,
           "Pawn vs king: opposition and outflanking.",
           ["Kc2", "Kc5", "Kd3"], "Approach from behind to win the pawn."),
    Puzzle("p084",
           "4k3/8/8/8/8/8/4PP2/4K2R w K - 0 1",
           "w", "mate_in_2", 4,
           "Back-rank weakness setup: bring the rook.",
           ["Rh8+"], "Rook sacrifice on h8."),
    Puzzle("p085",
           "r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/3P1N2/PPP2PPP/RNBQK2R w KQkq - 0 1",
           "w", "fork", 2,
           "Italian setup: Ng5 with threats.",
           ["O-O"], "Castle before launching Ng5."),
    Puzzle("p086",
           "8/8/8/3k4/3P4/3K4/8/8 w - - 0 1",
           "w", "endgame", 2,
           "Pawn promotion: opposition.",
           ["Kc3", "Kc6", "Kc4"], "Take opposition to push the pawn."),
    Puzzle("p087",
           "6k1/5ppp/8/8/8/2N5/5PPP/6K1 w - - 0 1",
           "w", "endgame", 3,
           "Knight and pawn vs king: fork or penetration.",
           ["Ne4"], "Ne4 controls key squares to support the pawn."),
    Puzzle("p088",
           "4k3/8/8/8/8/8/4PP2/4K2R w K - 0 1",
           "w", "mate_in_2", 4,
           "Castle the king to safety.",
           ["O-O"], "Castle, then check."),
    Puzzle("p089",
           "8/8/8/8/3k4/8/3K4/4R3 w - - 0 1",
           "w", "skewer", 2,
           "Rook skewer: push the king and attack the rook.",
           ["Re4+", "Kd5", "Ra4"], "Push king to edge, then attack."),
    Puzzle("p090",
           "r1bq1rk1/pppp1ppp/2n2n2/2b1p3/2B1P3/2N2N2/PPPP1PPP/R1BQ1RK1 w - - 0 1",
           "w", "tactics", 3,
           "Italian: look for the d4 break.",
           ["d3"], "Solid development, plan d4 to challenge the center."),
    Puzzle("p091",
           "8/8/8/8/4k3/8/4K3/4R3 w - - 0 1",
           "w", "endgame", 1,
           "Rook endgame: cut off the king.",
           [], "Cut off the king on the 3rd rank."),
    Puzzle("p092",
           "6k1/5ppp/8/8/8/2B5/5PPP/6K1 w - - 0 1",
           "w", "endgame", 2,
           "Bishop and pawn endgame: control promotion square.",
           ["Bd4", "Kf8", "Bf6"], "Control the key diagonal to support promotion."),
    Puzzle("p093",
           "4k3/8/8/8/8/8/4PP2/4K2R w K - 0 1",
           "w", "mate_in_2", 4,
           "Castle into safety then push pawns.",
           ["O-O"], "Castle and prepare the f-pawn push."),
    Puzzle("p094",
           "r1bqr1k1/ppp2ppp/2n5/3p4/1b1P4/2N5/PPP1QPPP/R1B1R1K1 w - - 0 1",
           "w", "pin", 4,
           "Pin the bishop to win material.",
           ["a3", "Bxc3"], "Force bishop, then capture with check."),
    Puzzle("p095",
           "8/8/8/3k4/8/3K4/3P4/8 w - - 0 1",
           "w", "endgame", 3,
           "Pawn vs king: push with king support.",
           [], "Opposition, then pawn push."),
    Puzzle("p096",
           "4k3/8/4K3/8/8/8/4P3/8 w - - 0 1",
           "w", "endgame", 2,
           "Pawn promotion with active king.",
           [], "Approach the pawn from the side."),
    Puzzle("p097",
           "6k1/5ppp/8/8/8/2N5/5PPP/6K1 w - - 0 1",
           "w", "endgame", 3,
           "Knight vs king: push the king to the edge.",
           ["Ne4", "Kf8", "Nd6+"], "Knight dance: chase the king."),
    Puzzle("p098",
           "4k3/8/8/8/8/8/4PP2/4K2R w K - 0 1",
           "w", "mate_in_2", 3,
           "Rook lift and back-rank mate.",
           ["Rh8+"], "Rook sacrifice to expose the king."),
    Puzzle("p099",
           "8/8/8/8/3k4/8/3K4/4R3 w - - 0 1",
           "w", "skewer", 2,
           "Rook endgame: cut off and skewer.",
           ["Re3", "Kd5", "Ra3"], "Cut off the king, then attack."),
    Puzzle("p100",
           "r1bqkbnr/pppp1ppp/2n5/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 1",
           "w", "opening_trap", 1,
           "Italian setup: develop and castle.",
            ["O-O"], "Castle to prepare the kingside attack.")]


def get_all_puzzles() -> list[Puzzle]:
    """Return a copy of the full puzzle list."""
    return list(PUZZLES)


def get_puzzle_by_id(puzzle_id: str) -> Puzzle | None:
    for p in PUZZLES:
        if p.id == puzzle_id:
            return p
    return None


def get_puzzles_by_theme(theme: str) -> list[Puzzle]:
    return [p for p in PUZZLES if p.theme == theme]


def get_puzzles_by_difficulty(level: int) -> list[Puzzle]:
    return [p for p in PUZZLES if p.difficulty == level]


def random_puzzle(seed: int | None = None) -> Puzzle:
    """Pick a random puzzle, optionally seeded for reproducibility."""
    import random
    rng = random.Random(seed)
    return rng.choice(PUZZLES)
